name: "Final - CI build with Maven (with DB) & docker build"

on:
#  push:
#    branches:
#    - master
  workflow_dispatch:  

jobs:
  build:
    env:
      app_name: "springbootapp"
      docker_repo: ${{ vars.TEST_REPO }}
    name: build the jar
    runs-on: ubuntu-latest
    #Deploy sql
    services:
      db:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root#123456
          MYSQL_DATABASE: testdb
        ports:
          - 3306:3306
        
    steps:
    #build the jar
      - name: check out code
        uses:  actions/checkout@v4
      
      - name: Set up open JDK 17
        uses: actions/setup-java@v4.6.0
        with:
          distribution: 'adopt'
          java-version: '17'
          
      - name: Build with maven
        run: mvn -B package -f pom.xml

      #build docker image
        
      - name: Debug - print ENV
        run: echo "App Name - ${{env.app_name}}, repo - ${{vars.TEST_REPO}} , Commit SHA - ${{ github.sha }}"
        
      - name: Build Docker image  
        run: docker build -t "${{env.app_name}}:${{ github.sha }}" .
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Push to Docker Hub
        run: |
          docker tag "${{env.app_name}}:${{ github.sha }}" "${{vars.TEST_REPO}}":v1.1
          docker push "${{env.docker_repo}}":v1.1
