name: "CI build with Maven (with DB) & dockerize"

on:
#  push:
#    branches:
#    - master
  workflow_dispatch:  

jobs:
  build:
    name: job 1 -build the jar
    runs-on: ubuntu-latest
    services:
      db:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root#123456
          MYSQL_DATABASE: testdb
        ports:
          - 3306:3306
    steps:
      - uses:  actions/checkout@v4
      - name: Set up open JDK 17
        uses: actions/setup-java@v4.6.0
        with:
          distribution: 'adopt'
          java-version: '17'
      - name: Build with maven
        run: mvn -X package -f pom.xml
       # env:
        #  SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/testdb
         # SPRING_DATASOURCE_USERNAME: root
          #SPRING_DATASOURCE_PASSWORD: root
    
  
